# GitHub Pages configuration - for documentation site only
# This file does not affect the Flask application functionality

theme: jekyll-theme-slate
google_analytics: true
show_downloads: false
title: "Daft Image Playground"
description: "AI image search via Daft.ai, Flask, and BLIP"

# SEO and social media meta tags
url: "https://peckjon.github.io"
baseurl: "/daft-image-playground"
image: https://github.com/user-attachments/assets/9513c930-fc68-4ae4-b5d7-d5acfe702784

# Additional SEO settings for jekyll-seo-tag plugin
author: "peckjon"
robots: "index, follow"

# Twitter Card settings
twitter:
  card: summary_large_image
  username: peckjon

# Social media settings
social:
  name: "Daft Image Playground"
  links: 
    - https://github.com/peckjon/daft-image-playground

# SEO defaults for all pages
defaults:
  - scope:
      path: ""
    values:
      image: https://github.com/user-attachments/assets/9513c930-fc68-4ae4-b5d7-d5acfe702784
      type: website