# GitHub Pages configuration - for documentation site only
# This file does not affect the Flask application functionality

theme: jekyll-theme-slate
google_analytics: true
show_downloads: false
title: "Daft Image Playground"
description: "AI image search via Daft.ai, Flask, and BLIP"

# SEO and social media meta tags
image: https://github.com/user-attachments/assets/9513c930-fc68-4ae4-b5d7-d5acfe702784

# Additional SEO settings for jekyll-seo-tag plugin
social:
  name: "Daft Image Playground"
  links: [https://github.com/peckjon/daft-image-playground]

# Open Graph / Twitter Card defaults
defaults:
  - scope:
      path: ""
    values:
      image: https://github.com/user-attachments/assets/9513c930-fc68-4ae4-b5d7-d5acfe702784