# GitHub Pages configuration - for documentation site only
# This file does not affect the Flask application functionality

theme: jekyll-theme-hacker
google_analytics: true
show_downloads: false
title: "Image Playground using Daft.ai"