# GitHub Pages configuration - for documentation site only
# This file does not affect the Flask application functionality

theme: jekyll-theme-cayman
google_analytics: true
show_downloads: false
title: "Daft Image Playground"
description: "AI image search via Daft.ai, Flask, and BLIP"